---
- name: Add Cloud Ops Agent to hosts
  hosts: all
  become: true
  roles:
    - role: google-cloud-ops-agents-ansible
      vars:
        agent_type: monitoring

    - role: google-cloud-ops-agents-ansible
      vars:
        agent_type: logging
