---
# This file is the central configuration entrypoint for Molecule. With this file, you can configure each tool that Molecule will employ when testing the role.
dependency:
  name: galaxy
driver:
  name: delegated
  gcp_service_account_key: ${GOOGLE_APPLICATION_CREDENTIALS}
  gcp_project_id: ${PROJECT}
  zone: ${ZONE}
  region: ${REGION}
  ssh_user: ${SSH_USER}
  ssh_pub_key_file: "${SSH_KEY_FILE}.pub"
  ssh_key_file: ${SSH_KEY_FILE}
lint: |
  set -e
  yamllint .
  # TODO(rmoriar1): add back the ansible-lint routine once an updated version is available on the GCP_UBUNTU VM.
platforms:
#  - name: "ansible-windows-2012-test"
#    image_family: projects/windows-cloud/global/images/family/windows-2012-r2
#    machine_type: e2-medium
#    size_gb: 80
#    groups:
#      - windows
#      - windows-2012
  - name: "ansible-windows-2016-test"
    image_family: projects/windows-cloud/global/images/family/windows-2016
    machine_type: e2-medium
    size_gb: 80
    groups:
      - windows
      - windows-2016
  - name: "ansible-windows-2019-test"
    image_family: projects/windows-cloud/global/images/family/windows-2019
    machine_type: e2-medium
    size_gb: 80
    groups:
      - windows
      - windows-2019
provisioner:
  name: ansible
  inventory:
    group_vars:
      windows:
        ansible_user: test_user
        ansible_connection: winrm
        ansible_become: false
        ansible_winrm_server_cert_validation: ignore
      windows-2012:
        ansible_password: Q%]r7Mzdp.YD;Uy
      windows-2016:
        ansible_password: y5xF/@a:V=6Tv!^
      windows-2019:
        ansible_password: tB/lc6e|8;L>xbv
  playbooks:
    create: ../resources/playbooks/create.yml
    prepare: ../resources/playbooks/prepare.yml
    converge: ../resources/playbooks/converge.yml
    verify: ../resources/playbooks/verify.yml
    destroy: ../resources/playbooks/destroy.yml
verifier:
  name: ansible
