---
- name: Prepare
  hosts: all
  become: true

  tasks:
    - name: Create google auth directory
      file:
        path: /etc/google/auth
        state: directory
        mode: '0755'

    - name: Copy application credentials onto the VM
      copy:
        src: "{{ molecule_yml.driver.gcp_service_account_key }}"
        dest: /etc/google/auth/application_default_credentials.json
        mode: 0400

    - name: Install agent
      include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      vars:
        agent_type: "{{ lookup('env', 'AGENT_TYPE') | default('monitoring', True) }}"
        package_state: present
        version: "{{ lookup('env', 'VERSION') | default('latest', True) }}"

