---
# Verify the state of the container after the role has finished executing.
- name: Verify
  hosts: all
  become: true

  vars:
    agent_type: "{{ lookup('env', 'AGENT_TYPE') | default('monitoring', True) }}"
    package_name: "{{ 'stackdriver-agent' if agent_type=='monitoring' else 'google-fluentd' if agent_type == 'logging' else 'google-cloud-ops-agent' }}"

  tasks:
    - name: Ensure the agent is absent
      package:
        name: "{{ package_name }}"
        state: absent
      register: result

    - name: Assert the agent was already absent
      assert:
        that: result.changed == false
