---
# This playbook calls the role. Molecule will invoke this playbook with ansible-playbook and run it against an instance created by the driver.
- name: Converge
  hosts: all
  tasks:
    - name: Include google_cloud_ops_agents role
      include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      vars:
        agent_type: "{{ lookup('env', 'AGENT_TYPE') | default('monitoring', True) }}"
        package_state: absent
        testing: true
