---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint . -w role-name
platforms:
  - name: instance
    image: docker.io/${MOLECULE_DISTRO:-centos:8}
provisioner:
  name: ansible
verifier:
  name: ansible
