---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
<<<<<<< HEAD
  ansible-lint .
=======
  ansible-lint . -w role-name
>>>>>>> fe94545 (add tests and ci)
platforms:
  - name: instance
    image: ${MOLECULE_DISTRO:-geerlingguy/docker-debian10-ansible}
provisioner:
  name: ansible
verifier:
  name: ansible
