---
# Install dependencies needed in order to successfully run the shell script
- name: Prepare
  hosts: all
  tasks:
    - name: Install curl
      apt:
        name: curl
        state: present
        update_cache: true
      when: ansible_os_family == 'Debian'

    - name: Install apt-utils
      apt:
        name: apt-utils
        state: present
        update_cache: true
      when: ansible_os_family == 'Debian'

    - name: Install gnupg
      apt:
        name: gnupg
        state: present
        update_cache: true
      when: ansible_os_family == 'Debian'

    - name: Install agent
      include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      vars:
        agent_type: "{{ lookup('env', 'AGENT_TYPE') | default('monitoring', True) }}"
        package_state: present
        testing: True
