---
- name: Verify
  hosts: all
  tasks:
    - name: Ensure the agent is present
      package:
        name: stackdriver-agent
        state: present
      register: result

    - name: Assert the agent was already present
      assert:
        that: result.changed == false

    - name: Ensure the agent has started
      service:
        name: stackdriver-agent
        state: started
        use: service
      register: result

    - name: Assert the agent was already running
      assert:
        that: result.changed == false
