---
- name: Validate package_state
  assert:
    that: package_state in ["present", "absent"]
    msg: "Received invalid pacakge state: '{{ package_state }}'. The Cloud Ops Ansible role supports the following package states: 'present' and 'absent'."

when: package_state == 'present'
  block:
  - name: Create temp directory
    tempfile:
      path: /tmp
      state: directory
      suffix: cloud_ops_shell_scripts
    register: tempfolder

  - name: Download script
    get_url:
      url: https://dl.google.com/cloudagents/add-logging-agent-repo.sh
      dest: "{{ tempfolder.path }}/add-logging-agent-repo.sh"
      force: yes
      mode: 0755

  - name: Add repo and install agent
    command:
      chdir: "{{ tempfolder.path }}"
      cmd: "bash add-logging-agent-repo.sh --also-install --version={{ version }}"
    environment:
      REPO_CODENAME: "{{ ansible_distribution_release }}"
    register: result
    changed_when: "'No changes made.' not in result.stdout_lines"
    notify: restart logging agent

- name: Uninstall agent
  package:
    name: google-fluentd
    state: "{{ package_state }}"
#TODO(rmoriar1): Clean up the repo when package_state is absent.

- name: Copy main config file onto the remote machine
  copy:
    src: "{{ main_config_file }}"
    dest: /etc/google-fluentd/google-fluentd.conf
    force: yes
    mode: 0644
    validate: '/sbin/google-fluentd -tC %s'
  when: main_config_file|length > 0
  notify: restart logging agent

- name: Copy additional configs onto the remote machine
  copy:
    src: "{{ item }}"
    dest: /etc/google-fluentd/plugin/
    force: yes
    mode: 0644
    validate: '/sbin/google-fluentd -tC %s'
  with_fileglob:
    - "{{ additional_config_dir }}/*.conf"
  when: additional_config_dir|length > 0
  notify: restart logging agent
