---
- name: Validate package_state
  assert:
    that: package_state in ['present', 'absent']
    msg: "Received invalid package state: '{{ package_state }}'. The Cloud Ops Ansible role supports the following package states: 'present' and 'absent'."


- name: Create temp directory
  tempfile:
    path: /tmp
    state: directory
  register: tempfolder
  changed_when: false

- name: Download script
  get_url:
    url: https://dl.google.com/cloudagents/add-logging-agent-repo.sh
    dest: "{{ tempfolder.path }}/add-logging-agent-repo.sh"
    mode: 0755
  changed_when: false

- when: package_state == 'present'
  block:
  - name: Add repo and install agent
    command:
      chdir: "{{ tempfolder.path }}"
      cmd: "bash add-logging-agent-repo.sh --also-install --version={{ version }}"
    environment:
      REPO_CODENAME: "{{ ansible_distribution_release }}"
    register: result
    changed_when: "'No changes made.' not in result.stdout_lines"
    notify: restart logging agent

  - name: Copy main config file onto the remote machine
    copy:
      src: "{{ main_config_file }}"
      dest: /etc/google-fluentd/google-fluentd.conf
      force: yes
      mode: 0644
      validate: '/sbin/google-fluentd -tC %s'
    when: main_config_file|length > 0
    notify: restart logging agent

  - name: Copy additional configs onto the remote machine
    copy:
      src: "{{ item }}"
      dest: /etc/google-fluentd/plugin/
      force: yes
      mode: 0644
      validate: '/sbin/google-fluentd -tC %s'
    with_fileglob:
      - "{{ additional_config_dir }}/*.conf"
    when: additional_config_dir|length > 0
    notify: restart logging agent

- when: package_state == 'absent'
  block:
  - name: Uninstall agent and remove repo
  command:
    chdir: "{{ tempfolder.path }}"
    cmd: bash add-logging-agent-repo.sh --uninstall --remove_repo
  register: result
  changed_when: "'No changes made.' not in result.stdout_lines"

- name: Remove temp directory
    file:
      path: "{{ tempfolder.path }}"
      state: absent
    changed_when: false
  changed_when: false
