---
- name: Validate package_state
  assert:
    that: package_state in ["present", "absent"]
    msg: "Received invalid package state: '{{ package_state }}'. The Cloud Ops Ansible role supports the following package states: 'present' and 'absent'."

- name: Create temp directory
    tempfile:
      path: /tmp
      state: directory
    register: tempfolder
    changed_when: false

- name: Download script
    get_url:
      url: https://dl.google.com/cloudagents/add-logging-agent-repo.sh
      dest: "{{ tempfolder.path }}/add-logging-agent-repo.sh"
      force: yes
      mode: 0755

- when: package_state == "present"
  block:
  - name: Add repo and install agent
    command:
      chdir: /usr/local/bin/cloud_ops_scripts/
      cmd: "bash add-monitoring-agent-repo.sh --also-install --version={{ version }}"
    environment:
      REPO_CODENAME: "{{ ansible_distribution_release }}"
    register: result
    changed_when: "'No changes made.' not in result.stdout_lines"
    notify: restart monitoring agent

  - name: Copy main config file onto the remote machine
    copy:
      src: "{{ main_config_file }}"
      dest: /etc/stackdriver/collectd.conf
      force: yes
      mode: 0644
      validate: '/opt/stackdriver/collectd/sbin/stackdriver-collectd -tC %s'
    when: main_config_file|length > 0
    notify: restart monitoring agent

  - name: Copy additional configs onto the remote machine
    copy:
      src: "{{ item }}"
      dest: /etc/stackdriver/collectd.d/
      force: yes
      mode: 0644
      validate: '/opt/stackdriver/collectd/sbin/stackdriver-collectd -tC %s'
    with_fileglob:
      - "{{ additional_config_dir }}/*.conf"
    when: additional_config_dir|length > 0

- name: Uninstall agent and remove repo
  command:
    chdir: /usr/local/bin/cloud_ops_scripts/
    cmd: bash add-monitoring-agent-repo.sh --uninstall
  register: result
  changed_when: "'No changes made.' not in result.stdout_lines"
  when: package_state == "absent"

- name: Remove temp directory
    file:
      path: "{{ tempfolder.path }}"
      state: absent
    changed_when: false
