---
- name: Fail if package state is not supported
  assert:
    that: package_state in ["present", "absent"]
    msg: "Received invalid package state: '{{ package_state }}'. The Cloud Ops Ansible role supports the following package states: 'present' and 'absent'."

- block:
  - name: Download script
    get_url:
      url: https://dl.google.com/cloudagents/add-monitoring-agent-repo.sh
      dest: /tmp/add-monitoring-agent-repo.sh
      force: yes
      mode: 0755

  - name: Add repo
    command:
      chdir: /tmp
      cmd: bash add-monitoring-agent-repo.sh
    notify: restart monitoring agent

  when: package_state == "present"

- name: Install or uninstall agent
  package:
    name: "{{ monitoring_package_name }}"
    state: "{{ package_state }}"
#TODO(rmoriar1): Clean up the repo when package_state is absent.

- name: Copy main config file onto the remote machine
  copy:
    src: "{{ main_config_file }}"
    dest: /etc/stackdriver/collectd.conf
    force: yes
    mode: 0644
    validate: "{{ monitoring_binary }} -tC %s"
  when: main_config_file|length > 0
  notify: restart monitoring agent

- name: Copy additional configs onto the remote machine
  copy:
    src: "{{ item }}"
    dest: /etc/stackdriver/collectd.d/
    force: yes
    mode: 0644
    validate: "{{ monitoring_binary }} -tC %s"
  with_fileglob:
    - "{{ additional_config_dir }}/*.conf"
  when: additional_config_dir|length > 0
  notify: restart monitoring agent
