---
- name: Validate agent_type
  assert:
    that: agent_type == 'ops-agent'
    msg: "Received invalid agent type: '{{ agent_type }}'. The Cloud Ops Ansible role supports the following agents for Windows: 'ops-agent'."

- name: Create temp directory
  win_tempfile:
    path: "/Users/{{ ansible_user }}/AppData/Local/Temp"
    state: directory
    suffix: _cloud_ops_shell_scripts
  register: tempfolder
  check_mode: false
  changed_when: false

- name: Download script
  win_get_url:
    url: "https://dl.google.com/cloudagents/add-google-cloud-ops-agent-repo.ps1"
    dest: "{{ tempfolder.path }}/add-google-cloud-ops-agent-repo.ps1"
  check_mode: false
  changed_when: false

- name: Add repo and install agent or remove repo and uninstall agent
  win_shell: >
    .\\add-google-cloud-ops-agent-repo.ps1 {{ '-AlsoInstall' if package_state == 'present' else '-Uninstall -RemoveRepo' }} -Version {{ version }}
    {{ '-WhatIf' if ansible_check_mode else ''}}
  args:
    chdir: "{{ tempfolder.path }}"
  register: result
  check_mode: false
  changed_when: "'No changes made.' not in result.stdout_lines"
  notify: "restart ops-agent agent windows"

- when: package_state == 'present'
  block:
    - name: Copy main config file onto the remote machine
      win_copy:
        src: "{{ main_config_file }}"
        dest: 'C:\Program Files\Google\Cloud Operations\Ops Agent\config\config.yaml'
        force: true
      when: main_config_file | length > 0
      notify: "restart ops-agent agent windows"

- name: Remove temp directory
  win_file:
    path: "{{ tempfolder.path }}"
    state: absent
  check_mode: false
  changed_when: false
