---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint .
platforms:
  - name: instance
    image: ${MOLECULE_DISTRO:-geerlingguy/docker-debian10-ansible}
provisioner:
  name: ansible
verifier:
  name: ansible
