---
# Install dependencies needed in order to successfully run the shell script
- name: Prepare
  hosts: all
  tasks:
    - name: Install python2
      yum:
        name: python2
        state: present
        update_cache: true
      when: ansible_os_family == 'RedHat'

    - name: Install curl
      apt:
        name: curl
        state: present
        update_cache: true
      when: ansible_os_family == 'Debian'

    - name: Install apt-utils
      apt:
        name: apt-utils
        state: present
        update_cache: true
      when: ansible_os_family == 'Debian'

    - name: Install gnupg
      apt:
        name: gnupg
        state: present
        update_cache: true
      when: ansible_os_family == 'Debian'
