---
# Install dependencies needed in order to successfully run the shell script.
- name: Prepare
  hosts: all
  tasks:
  - when: ansible_os_family == 'Debian'
    block:
      - name: Install curl
        apt:
          name: curl
          state: present
          update_cache: true

      - name: Install apt-utils
        apt:
          name: apt-utils
          state: present
          update_cache: true

      - name: Install gnupg
        apt:
          name: gnupg
          state: present
          update_cache: true
