---
# Create network in gcp project, a subnet and a firewall rule.

- name: "create network {{ molecule_yml.driver.network_name }}"
  gcp_compute_network:
    name: "{{ molecule_yml.driver.network_name }}"
    state: present
    project: "{{ molecule_yml.driver.gcp_project_id }}"
    auth_kind: serviceaccount
    service_account_file: "{{ molecule_yml.driver.gcp_service_account_key }}"
  register: network

- name: "create firewall rule for ports 22, 3389 and 5986"
  gcp_compute_firewall:
    name: "{{ molecule_yml.driver.firewall_name }}"
    network: {"selfLink": "{{ network.selfLink }}"}
    allowed:
      - ip_protocol: tcp
        ports: ['22', '3389', '5986']
    target_tags:
      - ansibleinventory
    source_ranges: ['0.0.0.0/0']
    state: present
    project: "{{ molecule_yml.driver.gcp_project_id }}"
    auth_kind: serviceaccount
    service_account_file: "{{ molecule_yml.driver.gcp_service_account_key }}"
  register: firewall
