---
- name: set agent_type fact
  set_fact:
    agent_type: "{{ lookup('env', 'AGENT_TYPE') }}"

- name: "delete instance {{ item.name }}"
  gcp_compute_instance:
    name: "{{ item.name }}"
    zone: "{{ molecule_yml.driver.zone }}"
    state: absent
    project: "{{ molecule_yml.driver.gcp_project_id }}"
    auth_kind: serviceaccount
    service_account_file: "{{ molecule_yml.driver.gcp_service_account_key }}"
  register: instance

- name: delete address
  gcp_compute_address:
    name: "{{ item.name }}"
    region: "{{ molecule_yml.driver.region }}"
    state: absent
    project: "{{ molecule_yml.driver.gcp_project_id }}"
    auth_kind: serviceaccount
    service_account_file: "{{ molecule_yml.driver.gcp_service_account_key }}"
