---
- name: Create
  hosts: localhost
  connection: local

  tasks:
    - name: Create instances
      include_tasks: ./create_instance.yml
      loop: "{{ molecule_yml.platforms }}"

    - name: debug
      debug:
        msg: "{{ instance_created_linux }}"

    - name: debug
      debug:
        msg: "{{ instance_created_windows }}"

    - name: Initialize instance config dict
      set_fact:
        instance_conf_dict: []

    - name: Populate instance config dict linux
      set_fact:
        instance_conf_dict: >
          "{{ instance_conf_dict) }}" + [ {
          'instance': "{{ item.name }}",
          'address': "{{ item.networkInterfaces[0].accessConfigs[0].natIP }}",
          'user': "{{ molecule_yml.driver.ssh_user }}",
          'port': "22",
          'identity_file': "{{ molecule_yml.driver.ssh_key_file }}",
          'connection': "ssh", } ]
      with_items: "{{ instance_created_linux.instances }}"
      when: instance_created_linux.changed

    - name: debug
      debug:
        msg: "{{ instance_conf_dict }}"

    - name: Populate instance config dict windows
      set_fact:
        instance_conf_dict: >
          "{{ instance_conf_dict }}" + [ {
          'instance': "{{ item.name }}",
          'address': "{{ item.networkInterfaces[0].accessConfigs[0].natIP }}",
          'user': "{{ molecule_yml.driver.ssh_user }}",
          'port': "5986",
          'connection': "winrm", } ]
      with_items: "{{ instance_created_windows.instances }}"
      when: instance_created_windows.changed

    - name: debug
      debug:
        msg: "{{ instance_conf_dict }}"

#    - name: Convert instance config dict to a list
#      set_fact:
#        instance_conf: "{{ instance_config_dict.results | map(attribute='ansible_facts.instance_conf_dict') | list }}"
#      when: instance_created_linux.changed or instance_created_windows.changed

#    - name: debug
#      debug:
#        msg: "{{ instance_conf }}"

    - name: Dump instance config
      copy:
        content: "{{ instance_conf_dict | to_json | from_json }}"
        dest: "{{ molecule_instance_config }}"
      when: instance_created_linux.changed or instance_created_windows.changed

    - name: debug
      debug:
        msg: "{{ instance_conf_dicti | to_json | from_json }}"

    - name: Sleep five minutes to allow GCP instances to spin up
      pause:
        minutes: 1
