---
- name: "Delete instance {{ item.name }}"
  gcp_compute_instance:
    name: "{{ item.name }}"
    zone: "{{ molecule_yml.driver.zone }}"
    state: absent
    project: "{{ molecule_yml.driver.gcp_project_id }}"
    auth_kind: serviceaccount
    service_account_file: "{{ molecule_yml.driver.gcp_service_account_key }}"
  register: instance
  when: item.image_family | regex_search('windows') | length == 0
