---
# This file is the central configuration entrypoint for Molecule. With this file, you can configure each tool that Molecule will employ when testing the role.
dependency:
  name: galaxy
driver:
  name: delegated
  gcp_service_account_key: ${GOOGLE_APPLICATION_CREDENTIALS}
  gcp_project_id: ${PROJECT}
  zone: ${ZONE}
  region: ${REGION}
  ssh_user: ${SSH_USER}
  ssh_pub_key_file: "${SSH_KEY_FILE}.pub"
  ssh_key_file: ${SSH_KEY_FILE}
  network_name: "ansible-network-${AGENT_TYPE}-${MOLECULE_SCENARIO_NAME}"
  firewall_name: ansible-firewall
  ip_cidr_range: 172.16.0.0/28
lint: |
  set -e
  yamllint .
  ansible-lint .
platforms:
  - name: "ansible-centos-7-${AGENT_TYPE}-${MOLECULE_SCENARIO_NAME}"
    image_family: projects/centos-cloud/global/images/family/centos-7
    machine_type: e2-medium
    size_gb: 40
    groups:
      - centos
  - name: "ansible-centos-8-${AGENT_TYPE}-${MOLECULE_SCENARIO_NAME}"
    image_family: projects/centos-cloud/global/images/family/centos-8
    machine_type: e2-medium
    size_gb: 40
    groups:
      - centos
  - name: "ansible-rhel-7-${AGENT_TYPE}-${MOLECULE_SCENARIO_NAME}"
    image_family: projects/rhel-cloud/global/images/family/rhel-7
    machine_type: e2-medium
    size_gb: 40
    groups:
      - rhel
  - name: "ansible-rhel-8-${AGENT_TYPE}-${MOLECULE_SCENARIO_NAME}"
    image_family: projects/rhel-cloud/global/images/family/rhel-8
    machine_type: e2-medium
    size_gb: 40
    groups:
      - rhel
  - name: "ansible-ubuntu-1604-${AGENT_TYPE}-${MOLECULE_SCENARIO_NAME}"
    image_family: projects/ubuntu-os-cloud/global/images/family/ubuntu-1604-lts
    machine_type: e2-medium
    size_gb: 40
    groups:
      - ubuntu
  - name: "ansible-ubuntu-1804-${AGENT_TYPE}-${MOLECULE_SCENARIO_NAME}"
    image_family: projects/ubuntu-os-cloud/global/images/family/ubuntu-1804-lts
    machine_type: e2-medium
    size_gb: 40
    groups:
      - ubuntu
  - name: "ansible-ubuntu-2004-${AGENT_TYPE}-${MOLECULE_SCENARIO_NAME}"
    image_family: projects/ubuntu-os-cloud/global/images/family/ubuntu-2004-lts
    machine_type: e2-medium
    size_gb: 40
    groups:
      - ubuntu
  - name: "ansible-debian-9-${AGENT_TYPE}-${MOLECULE_SCENARIO_NAME}"
    image_family: projects/debian-cloud/global/images/family/debian-9
    machine_type: e2-medium
    size_gb: 40
    groups:
      - debian
  - name: "ansible-debian-10-${AGENT_TYPE}-${MOLECULE_SCENARIO_NAME}"
    image_family: projects/debian-cloud/global/images/family/debian-10
    machine_type: e2-medium
    size_gb: 40
    groups:
      - debian
  - name: "ansible-sles-15-${AGENT_TYPE}-${MOLECULE_SCENARIO_NAME}"
    image_family: projects/suse-cloud/global/images/family/sles-15
    machine_type: e2-medium
    size_gb: 40
    groups:
      - sles
provisioner:
  name: ansible
  playbooks:
    create: ../resources/playbooks/create.yml
    destroy: ../resources/playbooks/destroy.yml
    prepare: ../resources/playbooks/prepare.yml
verifier:
  name: ansible
